// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "使用用户名和密码登录，返回 JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "token": {
                                    "type": "string"
                                },
                                "user": {
                                    "$ref": "#/definitions/model.UserResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/herbs": {
            "get": {
                "description": "分页查询单味药，支持关键词搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "herbs"
                ],
                "summary": "获取单味药列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/definitions/model.HerbBasic"
                                    }
                                },
                                "page": {
                                    "type": "integer"
                                },
                                "page_size": {
                                    "type": "integer"
                                },
                                "total": {
                                    "type": "integer",
                                    "format": "int64"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/herbs/{id}": {
            "get": {
                "description": "根据 ID 获取单味药详细信息，包括毒性成分和名家经验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "herbs"
                ],
                "summary": "获取单味药详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "药物 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "$ref": "#/definitions/service.HerbDetail"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Expertise": {
            "type": "object",
            "properties": {
                "abstract": {
                    "type": "string"
                },
                "application_situation": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "clinical_case": {
                    "type": "string"
                },
                "couplet": {
                    "type": "string"
                },
                "dosage_course_usage": {
                    "type": "string"
                },
                "herb_id": {
                    "type": "integer"
                },
                "herb_or_decoction": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "link_article": {
                    "type": "string"
                },
                "related_article": {
                    "type": "string"
                },
                "related_literature": {
                    "type": "string"
                }
            }
        },
        "model.HerbBasic": {
            "type": "object",
            "properties": {
                "adr": {
                    "type": "string"
                },
                "basis_for_usage_and_dosage": {
                    "type": "string"
                },
                "clinical_suggestion": {
                    "type": "string"
                },
                "clinical_suggestion_basis": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "crowd_taboo": {
                    "type": "string"
                },
                "functionality": {
                    "type": "string"
                },
                "functionality_basis": {
                    "type": "string"
                },
                "herb_name": {
                    "type": "string"
                },
                "herb_name_pinyin": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "link_to_clinical_suggestion": {
                    "type": "string"
                },
                "link_to_functionality_basis": {
                    "type": "string"
                },
                "link_to_usage_and_dosage": {
                    "type": "string"
                },
                "pathological_examination": {
                    "type": "string"
                },
                "symptom_contraindications": {
                    "type": "string"
                },
                "toxicity_mechanism": {
                    "type": "string"
                },
                "typical_cases_of_adr": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "usage_and_dosage": {
                    "type": "string"
                },
                "virulence": {
                    "type": "string"
                }
            }
        },
        "model.HerbToxicCompound": {
            "type": "object",
            "properties": {
                "cas": {
                    "type": "string"
                },
                "compound_name": {
                    "type": "string"
                },
                "compound_type": {
                    "type": "string"
                },
                "herb_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "molecular_formula": {
                    "type": "string"
                },
                "record_number": {
                    "type": "integer"
                }
            }
        },
        "model.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.HerbDetail": {
            "type": "object",
            "properties": {
                "adr": {
                    "type": "string"
                },
                "basis_for_usage_and_dosage": {
                    "type": "string"
                },
                "clinical_suggestion": {
                    "type": "string"
                },
                "clinical_suggestion_basis": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "crowd_taboo": {
                    "type": "string"
                },
                "expertises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Expertise"
                    }
                },
                "functionality": {
                    "type": "string"
                },
                "functionality_basis": {
                    "type": "string"
                },
                "herb_name": {
                    "type": "string"
                },
                "herb_name_pinyin": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "link_to_clinical_suggestion": {
                    "type": "string"
                },
                "link_to_functionality_basis": {
                    "type": "string"
                },
                "link_to_usage_and_dosage": {
                    "type": "string"
                },
                "pathological_examination": {
                    "type": "string"
                },
                "symptom_contraindications": {
                    "type": "string"
                },
                "toxic_compounds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.HerbToxicCompound"
                    }
                },
                "toxicity_mechanism": {
                    "type": "string"
                },
                "typical_cases_of_adr": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "usage_and_dosage": {
                    "type": "string"
                },
                "virulence": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "AI Medical Agent API",
	Description:      "中医药知识库 API 服务 —— 方剂、单味药、对药、论文、分子信息、名家经验管理",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
